const lyrics = [
  {
    section: "Intro",
    lines: [
      "This fear is real",
      "This night is long",
      "But something deeper calls me on",
    ],
  },
  {
    section: "Verse 1",
    lines: [
      "Monday morning waits before me",
      "Like a mountain made of stone",
      "And I feel the weight of worry",
      "Like I have to stand alone",
      "",
      "But somewhere underneath the shaking",
      "Under all the fear I feel",
      "There is something still unbroken",
      "There is something steady, real",
    ],
  },
  {
    section: "Pre-Chorus",
    lines: [
      "So when the dark comes close",
      "And the worst begins to speak",
      "I will listen for the deeper voice",
      "That tells my soul to keep",
    ],
  },
  {
    section: "Chorus",
    lines: [
      "I will stand in the light",
      "Even when my heart is afraid",
      "Even when the road is uncertain",
      "Even when my courage shakes",
      "",
      "I am more than this fear",
      "I am more than this pain",
      "And whatever waits before me",
      "Will not take my faith away",
      "",
      "This trial may test me",
      "But it will not erase me",
      "I will stand in the light",
    ],
  },
  {
    section: "Verse 2",
    lines: [
      "I do not need to know the ending",
      "To take the next right breath",
      "I do not need to feel unbroken",
      "To keep walking through the test",
      "",
      "There is strength inside the trembling",
      "There is hope inside the strain",
      "And the soul that has survived so much",
      "Can rise again, again",
    ],
  },
  {
    section: "Pre-Chorus",
    lines: [
      "So if my hands are shaking",
      "That does not mean I fall",
      "It means I'm human in the moment",
      "And still answering the call",
    ],
  },
  {
    section: "Chorus",
    lines: [
      "I will stand in the light",
      "Even when my heart is afraid",
      "Even when the road is uncertain",
      "Even when my courage shakes",
      "",
      "I am more than this fear",
      "I am more than this pain",
      "And whatever waits before me",
      "Will not take my faith away",
      "",
      "This trial may test me",
      "But it will not erase me",
      "I will stand in the light",
    ],
  },
  {
    section: "Bridge",
    lines: [
      "Let truth be louder than panic",
      "Let peace be stronger than dread",
      "Let every thought that rises against me",
      "Lose its power in my head",
      "",
      "I have walked through fire before this",
      "I have made it through the strain",
      "And I will not give this moment",
      "More power than my name",
      "",
      "So breathe, my soul, breathe slowly",
      "Stand, my heart, stand tall",
      "The night may speak in thunder",
      "But it does not speak for all",
    ],
  },
  {
    section: "Final Chorus",
    lines: [
      "I will stand in the light",
      "Even when my heart is afraid",
      "Even when the road is uncertain",
      "Even when my courage shakes",
      "",
      "I am more than this fear",
      "I am more than this pain",
      "And whatever waits before me",
      "Will not take my faith away",
      "",
      "This trial may test me",
      "But it will not erase me",
      "I will stand in the light",
    ],
  },
  {
    section: "Outro",
    lines: [
      "This fear is real",
      "But it is not my master",
      "Morning is coming",
      "And I will meet it standing",
    ],
  },
];

export default lyrics;
